#!/bin/sh
#
# htmlwdiff
# Requires: wdiff from ftp://ftp.gnu.org/gnu/wdiff/
#           mktemp (in the FreeBSD base system so I don't know where to
#		get it if you don't have it)
#
a1=`mktemp -t htmlwdiff1`
a2=`mktemp -t htmlwdiff2`
sed -e 's/&/&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' $1 > $a1
sed -e 's/&/&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' $2 > $a2
# This was originally meant to create a portion of a page that
# should be wrapped; however, it seems more common to just use it
# to create a page, so create html wrapper.  With luck, you can remove
# the wrapper with "grep -v 'html>'".
echo "<html><head><title>wdiff $1 $2</title></head><body>"
echo "<pre>"
wdiff -w "<strike><font color='red'>" -x "</font></strike>" -y "<strong><font color='green'>" -z "</font></strong>" $a1 $a2
echo "</pre>"
echo "</body></html>"
rm -f $a1
rm -f $a2
