
default = "default"
default1 = "default" "1"
insensitive = %i"insensitive"
sensitive = %s"sensitive"
sensitive-nonalpha = %s"1-2!3~"
hex = %x41.42.43
dec = %d68.69.70
bin = %b110000.110001.110010
two-str = "1st" "2nd"
two-hex = %x41 %x42.43
two-bin = %b110000 %b110001.110010
str-hex = "default" %x41
mixed1 = "dflt" "2" %b110000 %b110001.110010 %d32 %d33 %i"AB" %i"CD" %s"de" %s"fg" %x41 %x42 
dspace = %d32
mixed3 = %d33 "AB"
mixed4 = %i"AB" %b1000011 %i"DE"
